name: issue comment
on:
  issue_comment:
    types: [created, edited]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pip install PyGithub
      - name: test
        shell: python
        run: |
          from github import Github
          print('hello')
          ACCESS_TOKEN = "${{ secrets.GITHUB_TOKEN }}"
          REPO_NAME = 'ju-manns/pipeline-test'

          # Initialize the GitHub client
          g = Github(ACCESS_TOKEN)

          # Get the repository
          repo = g.get_repo(REPO_NAME)
          issues = repo.get_issues()
          for issue in issues:
              print(issue)
